approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "graphql-mongoose-subscriptions@*":
    peerDependencies:
      "graphql-subscriptions": "*"